import { PlacaMae } from "../../assets";
import { ProductsDTO } from "../../components";

export const PRODUCTS_DESTACT: ProductsDTO[] = [
  {
    id: "1",
    code: "ABC123",
    description: "Produto incrível",
    title: "Produto 1",
    src: PlacaMae,
    price: 19.99,
    descriptionCompleted: "Descrição completa do Produto 1",
  },
  {
    id: "2",
    code: "DEF456",
    description: "Outro produto incrível",
    title: "Produto 2",
    src: PlacaMae,
    price: 29.99,
    descriptionCompleted: "Descrição completa do Produto 2",
  },
  {
    id: "3",
    code: "GHI789",
    description: "Mais um produto incrível",
    title: "Produto 3",
    src: PlacaMae,
    price: 39.99,
    descriptionCompleted: "Descrição completa do Produto 3",
  },
  {
    id: "4",
    code: "JKL012",
    description: "Um produto fantástico",
    title: "Produto 4",
    src: PlacaMae,
    price: 49.99,
    descriptionCompleted: "Descrição completa do Produto 4",
  },
  {
    id: "45",
    code: "JKL012",
    description: "Um produto fantástico 7",
    title: "Produto 7",
    src: PlacaMae,
    price: 479.99,
    descriptionCompleted: "Descrição completa do Produto 7",
  },
  {
    id: "46",
    code: "JKL012",
    description: "Um produto fantástico 5",
    title: "Produto 5",
    src: PlacaMae,
    price: 469.99,
    descriptionCompleted: "Descrição completa do Produto 5",
  },
  {
    id: "47",
    code: "JKL012",
    description: "Um produto fantástico 6",
    title: "Produto 6",
    src: PlacaMae,
    price: 469.99,
    descriptionCompleted: "Descrição completa do Produto 6",
  },
];
