import { PlacaMae } from "../../assets";
import { ProductsDTO } from "../../components";

export const ALL_PRODUCTS: ProductsDTO[] = [
  {
    id: "1",
    code: "ABC123",
    description: "Produto incrível",
    title: "Produto 1",
    src: PlacaMae,
    price: 19.99,
    descriptionCompleted: "Descrição completa do Produto 1",
  },
  {
    id: "2",
    code: "DEF456",
    description: "Outro produto incrível",
    title: "Produto 2",
    src: PlacaMae,
    price: 29.99,
    descriptionCompleted: "Descrição completa do Produto 2",
  },
  {
    id: "3",
    code: "GHI789",
    description: "Mais um produto incrível",
    title: "Produto 3",
    src: PlacaMae,
    price: 39.99,
    descriptionCompleted: "Descrição completa do Produto 3",
  },
  {
    id: "4",
    code: "JKL012",
    description: "Um produto fantástico",
    title: "Produto 4",
    src: PlacaMae,
    price: 49.99,
    descriptionCompleted: "Descrição completa do Produto 4",
  },
  {
    id: "5",
    code: "MNO345",
    description: "Produto surpreendente",
    title: "Produto 5",
    src: PlacaMae,
    price: 59.99,
    descriptionCompleted: "Descrição completa do Produto 5",
  },
  {
    id: "6",
    code: "PQR678",
    description: "Incrível produto novo",
    title: "Produto 6",
    src: PlacaMae,
    price: 69.99,
    descriptionCompleted: "Descrição completa do Produto 6",
  },
  {
    id: "7",
    code: "STU901",
    description: "Produto exclusivo",
    title: "Produto 7",
    src: PlacaMae,
    price: 79.99,
    descriptionCompleted: "Descrição completa do Produto 7",
  },
  {
    id: "8",
    code: "VWX234",
    description: "Edição limitada",
    title: "Produto 8",
    src: PlacaMae,
    price: 89.99,
    descriptionCompleted: "Descrição completa do Produto 8",
  },
  {
    id: "89",
    code: "VWX234",
    description: "Edição limitada",
    title: "Produto 89",
    src: PlacaMae,
    price: 899.99,
    descriptionCompleted: "Descrição completa do Produto 8",
  },
  {
    id: "88",
    code: "VWX234",
    description: "Edição limitada",
    title: "Produto 88",
    src: PlacaMae,
    price: 889.99,
    descriptionCompleted: "Descrição completa do Produto 8",
  },
  {
    id: "87",
    code: "VWX234",
    description: "Edição limitada",
    title: "Produto 87",
    src: PlacaMae,
    price: 879.99,
    descriptionCompleted: "Descrição completa do Produto 8",
  },
  {
    id: "86",
    code: "VWX234",
    description: "Edição limitada",
    title: "Produto 86",
    src: PlacaMae,
    price: 869.99,
    descriptionCompleted: "Descrição completa do Produto 8",
  },
  {
    id: "85",
    code: "VWX234",
    description: "Edição limitada",
    title: "Produto 85",
    src: PlacaMae,
    price: 859.99,
    descriptionCompleted: "Descrição completa do Produto 8",
  },
];
